site_name: Yocto Hydrogreen
nav:
  - Project Details:
    - Overview: overview.md
    - Telemetry: telemetry.md
    - Hardware: hardware.md
  - Recipes: 
    - Overview: recipes/overview.md
    - Telemetry: recipes/telemetry.md
    - Telemetry Init: recipes/telemetry-init.md
    - Init IfUpDown: recipes/init-ifupdown.md
theme: readthedocs