site_name: Yocto Hydrogreen
nav:
  - Project Details:
    - Overview: overview.md
    - Telemetry: telemetry.md
    - Hardware: hardware.md
  - Implementation Details:
    - Recipes:
      - Telemetry: recipes/telemetry.md
      - Telemetry Init: recipes/telemetry-init.md
      - Init IfUpDown: recipes/init-ifupdown.md
theme: readthedocs