[package]
name = "rust-demo"
version = "0.1.0"
edition = "2021"
homepage = "https://hydrogreen.pl"
repository = "https://github.com/lizard123137/yocto-rp4"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.170"
termios = "0.3.3"
